// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ptO6SN61jmwZY9DvA9HW1emeR-9usjo',
    appId: '1:59064014171:web:9f82b02e2da73fd43db67e',
    messagingSenderId: '59064014171',
    projectId: 'taosil-2002bc',
    authDomain: 'taosil-2002bc.firebaseapp.com',
    storageBucket: 'taosil-2002bc.appspot.com',
    measurementId: 'G-Y3XMJWE48R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0ZMPpbUby9Ro9T_ftEg2CWPy0_ETK0o',
    appId: '1:59064014171:android:9498fa353bab434b3db67e',
    messagingSenderId: '59064014171',
    projectId: 'taosil-2002bc',
    storageBucket: 'taosil-2002bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSEttyRc5siIPTZDU5JaK0i4qVF747yM',
    appId: '1:59064014171:ios:dab2de6711382dc33db67e',
    messagingSenderId: '59064014171',
    projectId: 'taosil-2002bc',
    storageBucket: 'taosil-2002bc.appspot.com',
    iosClientId: '59064014171-87ubpjcu4itf3k7n9hm39ofctibd0pgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.taosil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSEttyRc5siIPTZDU5JaK0i4qVF747yM',
    appId: '1:59064014171:ios:dab2de6711382dc33db67e',
    messagingSenderId: '59064014171',
    projectId: 'taosil-2002bc',
    storageBucket: 'taosil-2002bc.appspot.com',
    iosClientId: '59064014171-87ubpjcu4itf3k7n9hm39ofctibd0pgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.taosil',
  );
}
